## The Framework
There is a good library in Python and this is numpy. [Numpy](https://numpy.org/) is bottom of the Python data science. Numpy is easy to use and many good libraries runs with numpy. Although Numpy is actually very fast on single cpu, many library tring to replace numpy because numpy can't operate on GPU or on parallel. There is numba but not it is not entirely covers all the details like scipy and scikit-learn<br/>
<b> Note: Performance is nothing without correct and unreadable code </b><br/>
<br/>
I've seen two good libraries that can replace the numpy: [Pytorch]((https://pytorch.org/)) and [Cupy](https://cupy.chainer.org/).<br/>
Cupy: is part of the chainer framework made by japanies startup company. Cupy can uses without chainer framework but isn't a full deep learning framework and it isn't in our scope right now.
<br/>

<br/>
I want to intruduce ported from lua torch and redesigned Pytorch. Pytorch has a very good interface to numpy and many operations similar to numpy users. It is a bit low level but it is good to research. In data science or deep learning people spend more time on research rather than production <br/>

Research framework doesn't mean to you can't use in production. Pytorch has a jit complier and compiles scripts to [torchscript](https://pytorch.org/docs/stable/jit.html) and than use in c++. In this way Pytorch bridges research and production.<br/>

### Philosophy of PyTorch
1. Stay out of the way<br/>
2. Cater to the impatient<br/>
3. Promote linear code-flow<br/>
4. Full interop with the Python ecosystem<br/>
5. Be as fast as anything else<br/>

## Tensor 
Tensor is the most essential part of the deep learning.<br/><br/>

In math numbers represented as <b>Scalar, Vector or Matrix</b> but In data science numbers represented as tensors. Basicly tensor is a <b>n dimensational array</b>(or the orher word <b>n rank array</b>).<br/>
<br/>
- A scalar is a 0 dimensional tensor
- A vector is a 1 dimensional tensor
- A matrix is a 2 dimensional tensor
- A nd-array is an n dimensional tensor
<br/><br/>
#### Stop using words like vector, array or matrix. <b>Everything is tensor in data science. I will use tensor all the time.</b>

In [1]:
import torch
import torchvision

# other 3rd party imports
import numpy as np

print("Cuda version: ", torch.version.cuda)
print("Cudnn enabled?: ", torch.backends.cudnn.enabled)
print("Cudnn version: ", torch.backends.cudnn.version())
print("torch version: ", torch.__version__)
print("torchvision version: ", torchvision.__version__)
print("numpy version: ", np.__version__)

Cuda version:  10.1
Cudnn enabled?:  True
Cudnn version:  7603
torch version:  1.4.0.dev20191202
torchvision version:  0.5.0.dev20191203
numpy version:  1.17.4


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Tensor backend uses: ", device)

Tensor backend uses:  cuda


Pytorch tensors can operate numpy like operations <br/>
note: I am using lastest versyion Pytorch, torchvision, cuda and cudnn right now. If you want to make a product than use stable version.

Yes, Pytorch uses Cuda but this doeesn't mean you cannot run if you don't have Nvidia Gpu. Actually if you don't have a big data and big model don't use Gpu. Coping data to gpu and get back it is very time consuming process. If you do wihout big data and big model you will lose time instead of increasing speed(I tested the speed in my computer).<br/>
There is also a weak support for amd gpus(rocm) but you have to use linux or mac and recompile everthing from scratch.
#### Okey! Let's cook<br/>
<img src="https://deeplizard.com/images/pizza-744405_1920.jpg" alt="pizza in stone oven">

In [3]:
t = torch.tensor([1,2,3])
print(t)
# to the device or GPU
print(t.cuda())
print(t.to(device))
# to the cpu
print(t.cpu())

tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3])


In [4]:
t = [
    [1,2,3,123],
    [4,5,6,456],
    [7,8,9,789],
]
t = torch.tensor(t)

print(t[0])
print(t[1])
print(t[2])

print(t[0][0])
print(t[1][0])
print(t[2][0])

print(t[0][1])
print(t[1][1])
print(t[2][1])

print(t[0][2])
print(t[1][2])
print(t[2][2])

print(t[0][3])
print(t[1][3])
print(t[2][3])

print(type(t))
print(t.size())
print(t.shape)
print("dimensions: ", len(t.shape))
print(torch.tensor(t.shape).prod())
print(t.numel())

tensor([  1,   2,   3, 123])
tensor([  4,   5,   6, 456])
tensor([  7,   8,   9, 789])
tensor(1)
tensor(4)
tensor(7)
tensor(2)
tensor(5)
tensor(8)
tensor(3)
tensor(6)
tensor(9)
tensor(123)
tensor(456)
tensor(789)
<class 'torch.Tensor'>
torch.Size([3, 4])
torch.Size([3, 4])
dimensions:  2
tensor(12)
12


In [5]:
print("reshaped t:", t.reshape(1,t.numel()))
print("shape of reshaped t:", t.reshape(1,t.numel()).shape)
print("t shape isn't changed(mutated) itself: \n", t)

reshaped t: tensor([[  1,   2,   3, 123,   4,   5,   6, 456,   7,   8,   9, 789]])
shape of reshaped t: torch.Size([1, 12])
t shape isn't changed(mutated) itself: 
 tensor([[  1,   2,   3, 123],
        [  4,   5,   6, 456],
        [  7,   8,   9, 789]])


## Pytorch Image Dimensaions
[Batch size, Color channels, Height, Width]<br/>
If you want to use numpy interface you should change dimensaion order.

### [Tensor attributes](https://deeplizard.com/learn/video/jexkKugTg04)
In the end of the day, Pytorch is a tensor implementation. All tensors have a type and type should match each other.<br/>
<table class="table table-sm table-hover">
                                                    <tbody>
                                                        <tr>
                                                            <th>Data type</th>
                                                            <th>dtype</th>
                                                            <th>CPU tensor</th>
                                                            <th>GPU tensor</th>
                                                        </tr>
                                                        <tr>
                                                            <td>32-bit floating point</td>
                                                            <td>torch.float32</td>
                                                            <td>torch.FloatTensor</td>
                                                            <td>torch.cuda.FloatTensor</td>
                                                        </tr>
                                                        <tr>
                                                            <td>64-bit floating point</td>
                                                            <td>torch.float64</td>
                                                            <td>torch.DoubleTensor</td>
                                                            <td>torch.cuda.DoubleTensor</td>
                                                        </tr>
                                                        <tr>
                                                            <td>16-bit floating point</td>
                                                            <td>torch.float16</td>
                                                            <td>torch.HalfTensor</td>
                                                            <td>torch.cuda.HalfTensor</td>
                                                        </tr>
                                                        <tr>
                                                            <td>8-bit integer (unsigned)</td>
                                                            <td>torch.uint8</td>
                                                            <td>torch.ByteTensor</td>
                                                            <td>torch.cuda.ByteTensor</td>
                                                        </tr>
                                                        <tr>
                                                            <td>8-bit integer (signed)</td>
                                                            <td>torch.int8</td>
                                                            <td>torch.CharTensor</td>
                                                            <td>torch.cuda.CharTensor</td>
                                                        </tr>
                                                        <tr>
                                                            <td>16-bit integer (signed)</td>
                                                            <td>torch.int16</td>
                                                            <td>torch.ShortTensor</td>
                                                            <td>torch.cuda.ShortTensor</td>
                                                        </tr>
                                                        <tr>
                                                            <td>32-bit integer (signed)</td>
                                                            <td>torch.int32</td>
                                                            <td>torch.IntTensor</td>
                                                            <td>torch.cuda.IntTensor</td>
                                                        </tr>
                                                        <tr>
                                                            <td>64-bit integer (signed)</td>
                                                            <td>torch.int64</td>
                                                            <td>torch.LongTensor</td>
                                                            <td>torch.cuda.LongTensor</td>
                                                        </tr>
                                                    </tbody>
                                                </table>

In [6]:
t = torch.Tensor()
print(type(t))
print(t.dtype)
print(t.device)
print(t.layout)

<class 'torch.Tensor'>
torch.float32
cpu
torch.strided


Types must match

In [7]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])
print(t1.dtype)
print(t2.dtype)
print(t1 * t2)
print((t1 * t2).dtype)

torch.int64
torch.float32
tensor([1., 4., 9.])
torch.float32


### Creating tensors using data
These are the primary ways of creating tensor objects (instances of the torch.Tensor class), with data (array-like) in PyTorch:

1. torch.Tensor(data)
2. torch.tensor(data)
3. torch.as_tensor(data)
4. torch.from_numpy(data)

<b>class constructor</b>: creates object but not with all parameters. exp:  torch.Tensor<br/>
<b>factory functions</b>: builds tensor objects for us. it allows more dynamic object creation. exp: torch.tensor, torch.as_tensor, torch.from_numpy

In [8]:
print("torch default dtype: ", torch.get_default_dtype())

torch default dtype:  torch.float32


In [9]:
data = np.array([1,2,3])
print("np.array([1,2,3]).dtype: ", np.array([1,2,3]).dtype)

# class constructor
o1 = torch.Tensor(data) # no dtype ;)
# all 3 of that factory functions
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)

print("Tensor: ", o1)
print("tensor: ", o2) # reflects input type
print("as_tensor: ", o3)
print("from_numpy: ", o4)

np.array([1,2,3]).dtype:  int32
Tensor:  tensor([1., 2., 3.])
tensor:  tensor([1, 2, 3], dtype=torch.int32)
as_tensor:  tensor([1, 2, 3], dtype=torch.int32)
from_numpy:  tensor([1, 2, 3], dtype=torch.int32)


Tensor creation has a little changes with different funcitons.<br/>
torch.tensor reflects input type.


In [10]:
# they are both the same
print(torch.tensor(np.array([1.,2.,3.])))
print(torch.tensor(np.array([1.,2.,3.]), dtype=torch.float64))

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


Value modification changes value differently<br/>
<table class="table table-sm table-hover">
                                                    <tbody>
                                                        <tr>
                                                            <th>
                                                                Share Data(much more fast)
                                                            </th>
                                                            <th>
                                                                Copy Data
                                                            </th>
                                                        </tr>
                                                        <tr>
                                                            <td>
                                                                torch.as_tensor() -> <b> best option </b>
                                                            </td>
                                                            <td>
                                                                torch.tensor() -> <b> best option </b>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td>
                                                                torch.from_numpy() {shares only with numpy}
                                                            </td>
                                                            <td>
                                                                torch.Tensor() {doesn't contaion any type}
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>


In [11]:
data = np.array([1,2,3])

o1 = torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)

data[0] = 0
data[1] = 0
data[2] = 120

# there is something happened. Exemine what is going on.
print("Tensor: ", o1) # no dtype ;)
print("tensor: ", o2) # reflects input type
print("as_tensor: ", o3)
print("from_numpy: ", o4)

Tensor:  tensor([1., 2., 3.])
tensor:  tensor([1, 2, 3], dtype=torch.int32)
as_tensor:  tensor([  0,   0, 120], dtype=torch.int32)
from_numpy:  tensor([  0,   0, 120], dtype=torch.int32)


In [12]:
# take is back to numpy
print(o3.numpy())
print(type(o3.numpy()))
print(o4.numpy())
print(type(o4.numpy()))

[  0   0 120]
<class 'numpy.ndarray'>
[  0   0 120]
<class 'numpy.ndarray'>


## Some of creation options

In [13]:
print("torch.eye(2): ", torch.eye(2))
print("torch.zeros(2,2): ", torch.zeros(2,2))
print("torch.ones(2,2): ", torch.ones(2,2))
print("torch.rand(2,2): ", torch.rand(2,2))

torch.eye(2):  tensor([[1., 0.],
        [0., 1.]])
torch.zeros(2,2):  tensor([[0., 0.],
        [0., 0.]])
torch.ones(2,2):  tensor([[1., 1.],
        [1., 1.]])
torch.rand(2,2):  tensor([[0.8031, 0.6033],
        [0.0572, 0.8267]])


## Tensor operations
### Flatten, Reshape, and Squeeze
Most of the time i have spent time on dimensions. There operations 

In [14]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
])
print(t.size())
print(t.shape)
print("dimensions: ", len(t.shape))
print(torch.tensor(t.shape).prod())
print(t.numel())

torch.Size([3, 4])
torch.Size([3, 4])
dimensions:  2
tensor(12)
12


### Reshape
There is a little bit difference with reshaping function<br/>
<b>contigious data</b>: Pytorch avoids the data coping to make operations faster even when concatenating or stuking tensors. Contigious mean data continuous in one piace on ram. If you want to create and copy all data into a new contigious array use contigious function.
- view: Operates on "contigious" data. if it is not. throws and error.
- reshape: if data contigious uses view otherwise makes contigious and then uses view
- resize: There isn't guanties to protect the number of data. It samples and creates a new tensor

In [15]:
# change the shape without changing the rank
print("t.reshape(1,12): ", t.reshape(1,12))
print("t.reshape(2,6): ", t.reshape(2,6))
print("t.reshape(3,4): ", t.reshape(3,4))
print("t.reshape(4,3): ", t.reshape(4,3))
print("t.reshape(6,2): ", t.reshape(6,2))
print("t.reshape(12,1): ", t.reshape(12,1))

t.reshape(1,12):  tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])
t.reshape(2,6):  tensor([[1, 1, 1, 1, 2, 2],
        [2, 2, 3, 3, 3, 3]])
t.reshape(3,4):  tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
t.reshape(4,3):  tensor([[1, 1, 1],
        [1, 2, 2],
        [2, 2, 3],
        [3, 3, 3]])
t.reshape(6,2):  tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [3, 3],
        [3, 3]])
t.reshape(12,1):  tensor([[1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3],
        [3]])


### Changing shape by squeezing and unsqueezing
squeeze(Expends): removes one dimension from tensor.<br/>
unsqueeze(Shirnks): adds one dimension from tensor.

In [16]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])
torch.Size([1, 12])


In [17]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])
torch.Size([12])


In [18]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])
torch.Size([1, 12])


### Flatten
removes all of the axis except for '1'. creates 1 dim.<br/>
To flatten a tensor, we need to have at least two axes. This makes it so that we are starting with something that is not already flat. Let’s look now at a hand written image of an eight from the MNIST dataset. This image has 2 distinct dimensions, height and width.
<img src="https://deeplizard.com/images/CNN%20Flatten%20Operation%20Visualized.png" alt="image and flattened output">

In [19]:
def flatten(t):
    t = t.reshape(1, -1) #calculates other dims
    t = t.squeeze()
    return t

In [20]:
flatten(t) # gives me squeezed version ;)

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [21]:
t.reshape(1,-1)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

## Concatenating tensors
We combine tensors using the cat() function, and the resulting tensor will have a shape that depends on the shape of the two input tensors.

In [22]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])
print(t1.shape)
print(t2.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [23]:
dim=0
print(torch.cat((t1, t2), dim=dim).shape)
print(torch.cat((t1, t2), dim=dim).shape[dim])
print(torch.cat((t1, t2), dim=dim)) # to the 0. dim

torch.Size([4, 2])
4
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [24]:
dim=1
print(torch.cat((t1, t2), dim=1).shape)
print(torch.cat((t1, t2), dim=1).shape[dim])
print(torch.cat((t1, t2), dim=dim)) # to the 1. dim

torch.Size([2, 4])
4
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


### Flattening specific axes of a tensor

In [25]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

each channel indicates it is a image
<pre class="prettyprint">&gt; t = t.reshape(3,1,4,4)
b=batch
c=channel
h=height
w=width
&gt; t
tensor(
b->[
c->[
    h->[
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1]
        ]
    ],
c->[
    h->[
         w->[2, 2, 2, 2],
         w->[2, 2, 2, 2],
         w->[2, 2, 2, 2],
         w->[2, 2, 2, 2]
        ]
    ],
c->[
    h->[
         w->[3, 3, 3, 3],
         w->[3, 3, 3, 3],
         w->[3, 3, 3, 3],
         w->[3, 3, 3, 3]
        ]
    ]
])
</pre>

In [26]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

We have the <b>first batch</b>
<pre class="prettyprint">
c->[
    h->[
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1]
        ]
    ],
...)
</pre>

In [27]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

We have the <b>first color</b> channel of the first image
<pre class="prettyprint">
    h->[
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1],
         w->[1, 1, 1, 1]
        ]
...)
</pre>

In [28]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

We have the <b>first row</b> of the color channel of the first image
<pre class="prettyprint">
         w->[1, 1, 1, 1],
...)
</pre>

In [29]:
t[0][0][0]

tensor([1, 1, 1, 1])

We have the <b>first pixel</b> of the first row of the color channel of the first image
<pre class="prettyprint">
         1
...)
</pre>

In [30]:
t[0][0][0][0]

tensor(1)

#### if you want to flatten the specific dimension you should use Pytorch flatten method
start_dim is tell us which axis start to flatten operation<br/>
start_dim=1; First access to the color channel

In [31]:
# the correct flatten
print("start_dim=1;")
print(t.shape)
print(t.flatten(start_dim=1).shape)
print(t.flatten(start_dim=1))

start_dim=1;
torch.Size([3, 1, 4, 4])
torch.Size([3, 16])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])


In [32]:
# just want to show what is going on.
print("start_dim=0;")
print(t.flatten(start_dim=0).shape)
print(t.flatten(start_dim=0))
print("\nstart_dim=2;")
print(t.flatten(start_dim=2).shape)
print(t.flatten(start_dim=2))
print("\nstart_dim=3;") # nothing happen :)
print(t.flatten(start_dim=3).shape)
print(t.flatten(start_dim=3))

start_dim=0;
torch.Size([48])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

start_dim=2;
torch.Size([3, 1, 16])
tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]])

start_dim=3;
torch.Size([3, 1, 4, 4])
tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])


# Element-wise tensor operations for deep learning

In [33]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [34]:
t1[0][0]

tensor(1.)

In [35]:
t2[0][0]

tensor(9.)

In [36]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [37]:
print(t1 + 2)
print(t1 - 2)
print(t1 * 2)
print(t1 / 2)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [38]:
print(t1.add(2))
print(t1.sub(2))
print(t1.mul(2))
print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


### Let's see broadcasting tensor like numpy

In [39]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [40]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [41]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

In [42]:
t1 + 2 == t1 + torch.tensor(
                np.broadcast_to(2, t1.shape)
                ,dtype=torch.float32
                )

tensor([[True, True],
        [True, True]])

In [43]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)
print(t1.shape)
print(t2.shape)

torch.Size([2, 2])
torch.Size([2])


In [44]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [45]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

I can make a comparison operations to the tensor with scalar values. Thanks to the broadcasting

In [46]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [47]:
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [48]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [49]:
t.gt(0)

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [50]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [51]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [52]:
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

Element-wise operations using functions

In [53]:
t.abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [54]:
t.sqrt()

tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [55]:
t.neg()

tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [56]:
t.neg().abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

## Tensor Reduction Ops for Deep Learning
A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor.

In [57]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [58]:
t.sum()

tensor(8.)

In [59]:
t.numel()

9

In [60]:
t.sum().numel() #chain the operations

1

In [61]:
t.sum().numel() < t.numel() #doesn't protect the number of elements

True

In [62]:
t.prod()

tensor(0.)

In [63]:
t.mean()

tensor(0.8889)

In [64]:
t.std()

tensor(1.1667)

Reduction operatrions on different dimensations. 
* Remember we are reducing with respect to axis

In [65]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
], dtype=torch.float32)
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

You can think dim. like 
- dim=0 => there isn't a bracket, you are accessing into all brackets
- dim=1 => there is a 1 bracket, you are accessing into all brackets except for 1 bracket

In [66]:
print(t.shape)
print(t.shape[0])
print(t.shape[1])
print(t[0])
print(t[1])
print(t[2])

torch.Size([3, 4])
3
4
tensor([1., 1., 1., 1.])
tensor([2., 2., 2., 2.])
tensor([3., 3., 3., 3.])


In [67]:
print(t[0] + t[1] + t[2])

tensor([6., 6., 6., 6.])


In [68]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [69]:
print(t[0].sum())
print(t[1].sum())
print(t[2].sum())

tensor(4.)
tensor(8.)
tensor(12.)


In [70]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

and there is a one thing to you should know. if you are don't use dim. parameter you are accesing to flatten version of tensor

In [85]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,5,0]
], dtype=torch.float32)
print(t.shape)

torch.Size([3, 4])


In [87]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 5., 0.])

In [73]:
t.max()

tensor(5.)

In [74]:
t.argmax() # couting from left to right and then top to bottom.

tensor(10)

Let's use dim.

In [75]:
t

tensor([[1., 0., 0., 2.],
        [0., 3., 3., 0.],
        [4., 0., 5., 0.]])

t.max(dim=0) highlighted
tensor([<br/>
        0->[[1., 0., 0., <b>2.</b>]],<br/>
        1->[[0., <b>3.</b>, 3., 0.]],<br/>
        2->[[<b>4.</b>, 0., <b>5.</b>, 0.]]
        <br/>])

In [76]:
t.max(dim=0) # returns 2 different tensor. First -> values, Second -> indices

torch.return_types.max(
values=tensor([4., 3., 5., 2.]),
indices=tensor([2, 1, 2, 0]))

In [77]:
t.argmax(dim=0) # just returns indices

tensor([2, 1, 2, 0])

t.max(dim=1) highlighted
tensor([<br/>
        [[1., 0., 0., <b>2.</b>]],<br/>
        [[0., <b>3.</b>, 3., 0.]],<br/>
        [[4., 0., <b>5.</b>, 0.]]<br/>
          0---1---2--3
        <br/>])

In [78]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 2]))

In [79]:
t.argmax(dim=1)

tensor([3, 2, 2])

### Accessing elements inside tensors

In [80]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [81]:
t.mean()

tensor(5.)

In [82]:
t.mean().item()

5.0

In [83]:
t.mean(dim=0).tolist() # to the python list

[4.0, 5.0, 6.0]

In [84]:
t.mean(dim=0).numpy() # to the numpy array

array([4., 5., 6.], dtype=float32)