In [1]:
from mxnet import nd

Get started

In [2]:
x = nd.array([1,2,3])
print(x)


[1. 2. 3.]
<NDArray 3 @cpu(0)>


In [3]:
y = nd.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]])
print(y)


[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
<NDArray 3x4 @cpu(0)>


In [4]:
nd.array(((1,2,3),(4,5,6)))


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>

In [8]:
x = nd.ones((2,3))
x


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [26]:
y = nd.random.uniform(-1, 1, (2,3))
y


[[-0.1248256  -0.40493077  0.783546  ]
 [-0.88657403  0.9273255  -0.45468742]]
<NDArray 2x3 @cpu(0)>

In [11]:
x = nd.full((2,3), 2.0)
x


[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>

In [12]:
(x.shape, x.size, x.dtype)

((2, 3), 6, numpy.float32)

Operations

In [13]:
x*y


[[ 0.17953277  1.3890069  -0.30538082]
 [ 0.49425483  0.58357644 -0.46247315]]
<NDArray 2x3 @cpu(0)>

In [14]:
y.exp()


[[1.0939187  2.0027144  0.85839546]
 [1.2803422  1.3388195  0.7935517 ]]
<NDArray 2x3 @cpu(0)>

In [15]:
nd.dot(x, y.T)


[[1.2631588 0.6153581]
 [1.2631588 0.6153581]]
<NDArray 2x2 @cpu(0)>

Indexing

In [27]:
print(y)
y[0, 0]


[[-0.1248256  -0.40493077  0.783546  ]
 [-0.88657403  0.9273255  -0.45468742]]
<NDArray 2x3 @cpu(0)>



[-0.1248256]
<NDArray 1 @cpu(0)>

In [29]:
y[0, 1]


[-0.40493077]
<NDArray 1 @cpu(0)>

In [30]:
y[1, 0]


[-0.88657403]
<NDArray 1 @cpu(0)>

In [31]:
y[1, 1]


[0.9273255]
<NDArray 1 @cpu(0)>

In [32]:
y[1,2]


[-0.45468742]
<NDArray 1 @cpu(0)>

In [33]:
y[:, 1:3]


[[-0.40493077  0.783546  ]
 [ 0.9273255  -0.45468742]]
<NDArray 2x2 @cpu(0)>

In [34]:
y[:, 1:3] = 2
y


[[-0.1248256   2.          2.        ]
 [-0.88657403  2.          2.        ]]
<NDArray 2x3 @cpu(0)>

In [35]:
y[1:2, 0:2] = 4
y


[[-0.1248256  2.         2.       ]
 [ 4.         4.         2.       ]]
<NDArray 2x3 @cpu(0)>

Converting between MXNet NDArray and NumPy